version: '3.8'

services:
  hello-service:
    build: 
      context: ./hello-service/Hello.Service
    container_name: medyan-hello
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - medyan-network

  api-gateway:
    build: 
      context: ./api-gateway/Api.Gateway
    container_name: medyan-gateway
    restart: unless-stopped
    ports:
      - "7000:7000"
    depends_on:
      - hello-service
    networks:
      - medyan-network

networks:
  medyan-network:
    driver: bridge
